// Code generated by "stringer -type=Protocol"; DO NOT EDIT.

package rawnet

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ProtoIPv4-2048]
	_ = x[ProtoIPv6-34525]
	_ = x[ProtoARP-2054]
	_ = x[ProtoRARP-32821]
	_ = x[ProtoXNS-1536]
}

const (
	_Protocol_name_0 = "ProtoXNS"
	_Protocol_name_1 = "ProtoIPv4"
	_Protocol_name_2 = "ProtoARP"
	_Protocol_name_3 = "ProtoRARP"
	_Protocol_name_4 = "ProtoIPv6"
)

func (i Protocol) String() string {
	switch {
	case i == 1536:
		return _Protocol_name_0
	case i == 2048:
		return _Protocol_name_1
	case i == 2054:
		return _Protocol_name_2
	case i == 32821:
		return _Protocol_name_3
	case i == 34525:
		return _Protocol_name_4
	default:
		return "Protocol(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
